[package]
name = "compgraph"
version = "0.1.0"
edition = "2021"

[lib]
name = "compgraph"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[dependencies]
env_logger = "0.9"
slab = "0.4.7"
log = "0.4"
